export const SATIRICAL_HEADLINES: string[] = [
  "Chris Bowen announces new plan to power cars with 'sheer optimism and a fair go'",
  "Local man remortgages house to fill up Hilux",
  "Angus Taylor proposes we simply 'find more fuel underground somewhere'",
  "BREAKING: Coles Express now accepting firstborn children as payment",
  "Government releases emergency fuel reserves, described as 'a drop in the ocean — literally'",
  "Price of fuel now higher than Melbourne house deposit (per litre, adjusted for vibes)",
  "Cyclist smugly arrives at work, gets keyed anyway",
  "Australians rediscover the lost art of walking, immediately complain",
  "Treasurer assures nation 'the fundamentals are strong' while filling up a Corolla for $147",
  "Man who bought Tesla in 2023 now insufferable at every barbecue",
  "Sydney commuter considers selling kidney to fund weekly petrol costs",
  "EXCLUSIVE: Oil company CEO's tears found to be premium unleaded",
  "Report: Average Australian now spending more on fuel than avocado toast",
  "Opposition promises to lower fuel prices using 'different vibes'",
  "Scientists confirm: screaming at the bowser does not reduce prices",
  "Nation's utes form support group: 'We didn't ask for 120L tanks'",
  "Fuel price now measured in 'thoughts and prayers per litre'",
  "Local servo installs tissue box next to price display",
  "Breaking: Walking declared 'un-Australian' by motoring lobby",
  "Government announces new fuel subsidy — a firm handshake and a meat pie",
];
